name: Show information
on: {} # [push, pull_request]

jobs:
  build:
    name: Show information of github object
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Print github object
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | tee change-list.txt

