name: Show information
on: [push]

jobs:
  build:
    name: Try pushing to another repository
    runs-on: ubuntu-latest
    steps:
      - name: show GITHUB_WORKSPACE
        run: "echo $GITHUB_WORKSPACE"
      - name: Show pwd and ls
        run: |
          pwd
          tree ../
      - name: Clone myself
        uses: actions/checkout@v2
      - name: Show pwd and ls
        run: |
          pwd
          tree ../
      - name: Clone another repo
        uses: actions/checkout@v2
        with:
          repository: 'TonalidadeHidrica/github-actions-test-2'
          path: "../github-actions-test-2"
      - name: Show pwd and ls
        run: |
          pwd
          tree ../
