name: Show information
on: [push]

jobs:
  build:
    name: Try pushing to another repository
    runs-on: ubuntu-latest
    steps:
      - name: Clone myself
        uses: actions/checkout@v2
      - name: Show pwd and ls
        run: |
          pwd
          ls -al
      - name: Clone another repo
        uses: actions/checkout@v2
        with:
          repository: 'TonalidadeHidrica/github-actions-test-2'
      - name: Show pwd and ls
        run: |
          pwd
          ls -al
