name: Show information
on: [push]

jobs:
  build:
    name: Try pushing to another repository
    runs-on: ubuntu-latest
    steps:
      - name: Clone myself
        uses: actions/checkout@v2
        with:
          path: "github-actions-test"
      - name: Clone another repo
        uses: actions/checkout@v2
        with:
          repository: 'TonalidadeHidrica/github-actions-test-2'
          path: "github-actions-test-2"
      - name: Pseudo-run
        run: |
          cd github-actions-test
          find a
      - name: Pseudo-commit
        run: |
          pwd
          cd github-actions-test-2
          pwd
          date > date.log
          date=`date`
          git add .
          if ! git diff-index --quiet HEAD --
          then
            git -c user.name="bot" -c user.email="<>" commit --author="bot <>" --message="Test commit as of ${date}"
          fi
          git push
